# permissions for end users to view iampolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iampolicy-viewer-role
rules:
- apiGroups:
  - crd.k8s.otproc.com.otproc.com
  resources:
  - iampolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.k8s.otproc.com.otproc.com
  resources:
  - iampolicies/status
  verbs:
  - get
