---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crd.k8s.otproc.com.otproc.com
  resources:
  - iampolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.k8s.otproc.com.otproc.com
  resources:
  - iampolicies/finalizers
  verbs:
  - update
- apiGroups:
  - crd.k8s.otproc.com.otproc.com
  resources:
  - iampolicies/status
  verbs:
  - get
  - patch
  - update
